[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd server && npm start"